config/routes.rb
Trellin::Application.routes.draw do

  resources :tracks

  resources :credentials

  resources :users

  resources :text_blocks
  resources :proses
  resources :abilities

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match 'logout', to: 'sessions#logout'

  match 'index' => 'static#index'
  match 'history' => 'trellin#history'
  match 'creation' => 'trellin#creation'
  match 'time' => 'trellin#time'
  match 'background' => 'trellin#background'
  match 'board' => 'trellin#board'
  match 'level_chart' => 'trellin#level_chart'
  match 'encounter' => 'trellin#encounter'
  match 'organizations' => 'trellin#organizations'
  match 'push' => 'trellin#push'

  root :to => 'static#index'

end

app/models/text_block.rb
class TextBlock < ActiveRecord::Base
  acts_as_taggable
end

app/controllers/text_blocks_controller.rb
class TextBlocksController < ApplicationController
  # GET /text_blocks
  # GET /text_blocks.json
  def index
    @text_blocks = TextBlock.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @text_blocks }
    end
  end

  # GET /text_blocks/1
  # GET /text_blocks/1.json
  def show
    @text_block = TextBlock.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @text_block }
    end
  end

  # GET /text_blocks/new
  # GET /text_blocks/new.json
  def new
    @text_block = TextBlock.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @text_block }
    end
  end

  # GET /text_blocks/1/edit
  def edit
    @text_block = TextBlock.find(params[:id])
  end

  # POST /text_blocks
  # POST /text_blocks.json
  def create
    @text_block = TextBlock.new(params[:text_block])

    respond_to do |format|
      if @text_block.save
        format.html { redirect_to @text_block, notice: 'Text block was successfully created.' }
        format.json { render json: @text_block, status: :created, location: @text_block }
      else
        format.html { render action: "new" }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /text_blocks/1
  # PUT /text_blocks/1.json
  def update
    @text_block = TextBlock.find(params[:id])

    respond_to do |format|
      if @text_block.update_attributes(params[:text_block])
        format.html { redirect_to @text_block, notice: 'Text block was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @text_block.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /text_blocks/1
  # DELETE /text_blocks/1.json
  def destroy
    @text_block = TextBlock.find(params[:id])
    @text_block.destroy

    respond_to do |format|
      format.html { redirect_to text_blocks_url }
      format.json { head :ok }
    end
  end
end

app/helpers/text_blocks_helper.rb
module TextBlocksHelper
end

app/views/text_blocks/_form.html.erb
<%= form_for(@text_block) do |f| %>
  <% if @text_block.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text_block.errors.count, "error") %> prohibited this text_block from being saved:</h2>

      <ul>
      <% @text_block.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :tag_list %><br />
    <%= f.text_field :tag_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/text_blocks/edit.html.erb
<h1>Editing text_block</h1>

<%= render 'form' %>

<%= link_to 'Show', @text_block %> |
<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/index.html.erb
<h1>Listing text_blocks</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @text_blocks.each do |text_block| %>
  <tr>
    <td><%= text_block.title %></td>
    <td><%= text_block.content %></td>
    <td><%= link_to 'Show', text_block %></td>
    <td><%= link_to 'Edit', edit_text_block_path(text_block) %></td>
    <td><%= link_to 'Destroy', text_block, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Text block', new_text_block_path %>

app/views/text_blocks/new.html.erb
<h1>New text_block</h1>

<%= render 'form' %>

<%= link_to 'Back', text_blocks_path %>

app/views/text_blocks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @text_block.title %>
</p>

<p>
  <b>Tags:</b>
  <%= @text_block.tags %>
</p>

<p>
  <b>Content:</b>
  <%= @text_block.content %>
</p>


<%= link_to 'Edit', edit_text_block_path(@text_block) %> |
<%= link_to 'Back', text_blocks_path %>