config/routes.rb
Trellin::Application.routes.draw do

  resources :tracks

  resources :credentials

  resources :users

  resources :text_blocks
  resources :proses
  resources :abilities

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match 'logout', to: 'sessions#logout'

  match 'index' => 'static#index'
  match 'history' => 'trellin#history'
  match 'creation' => 'trellin#creation'
  match 'time' => 'trellin#time'
  match 'background' => 'trellin#background'
  match 'board' => 'trellin#board'
  match 'level_chart' => 'trellin#level_chart'
  match 'encounter' => 'trellin#encounter'
  match 'organizations' => 'trellin#organizations'
  match 'push' => 'trellin#push'

  root :to => 'static#index'

end

app/models/ability.rb
class Ability < ActiveRecord::Base

  belongs_to :track
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  # GET /abilities
  # GET /abilities.json
  def index
    @abilities = Ability.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @abilities }
    end
  end

  # GET /abilities/1
  # GET /abilities/1.json
  def show
    @ability = Ability.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ability }
    end
  end

  # GET /abilities/new
  # GET /abilities/new.json
  def new
    @ability = Ability.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ability }
    end
  end

  # GET /abilities/1/edit
  def edit
    @ability = Ability.find(params[:id])
  end

  # POST /abilities
  # POST /abilities.json
  def create
    @ability = Ability.new(params[:ability])

    respond_to do |format|
      if @ability.save
        format.html { redirect_to :abilities, notice: 'Ability was successfully created.' }
        format.json { render json: @ability, status: :created, location: @ability }
      else
        format.html { render action: "new" }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /abilities/1
  # PUT /abilities/1.json
  def update
    @ability = Ability.find(params[:id])

    respond_to do |format|
      if @ability.update_attributes(params[:ability])
        format.html { redirect_to @ability, notice: 'Ability was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abilities/1
  # DELETE /abilities/1.json
  def destroy
    @ability = Ability.find(params[:id])
    @ability.destroy

    respond_to do |format|
      format.html { redirect_to abilities_url }
      format.json { head :ok }
    end
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/views/abilities/_form.html.erb
<%= form_for(@ability) do |f| %>
  <% if @ability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ability.errors.count, "error") %> prohibited this ability from being saved:</h2>

      <ul>
	<% @ability.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :desc %><br />
    <%= f.text_area :desc, :class => 'gm_text_area' %>
  </div>

  <div class="actions">
    <%= f.submit :class => 'btn' %>
  </div>
<% end %>

app/views/abilities/edit.html.erb
<div class="container">
  <h1>Editing ability</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @ability %> |
  <%= link_to 'Back', abilities_path %>
</div>

app/views/abilities/index.html.erb
<h1>Listing abilities</h1>

<table>
  <tr>
    <th>Desc</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @abilities.each do |ability| %>
  <tr>
    <td><%= ability.desc %></td>
    <td><%= ability.name %></td>
    <td><%= link_to 'Show', ability %></td>
    <td><%= link_to 'Edit', edit_ability_path(ability) %></td>
    <td><%= link_to 'Destroy', ability, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ability', new_ability_path %>

app/views/abilities/new.html.erb
<div class="container">
  <h1>New ability</h1>

  <%= render 'form' %>

  <%= link_to 'Back', abilities_path %>
</div>

app/views/abilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Desc:</b>
  <%= @ability.desc %>
</p>

<p>
  <b>Name:</b>
  <%= @ability.name %>
</p>


<%= link_to 'Edit', edit_ability_path(@ability) %> |
<%= link_to 'Back', abilities_path %>