config/routes.rb
Trellin::Application.routes.draw do

  resources :tracks

  resources :credentials

  resources :users

  resources :text_blocks
  resources :proses
  resources :abilities

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  match 'logout', to: 'sessions#logout'

  match 'index' => 'static#index'
  match 'history' => 'trellin#history'
  match 'creation' => 'trellin#creation'
  match 'time' => 'trellin#time'
  match 'background' => 'trellin#background'
  match 'board' => 'trellin#board'
  match 'level_chart' => 'trellin#level_chart'
  match 'encounter' => 'trellin#encounter'
  match 'organizations' => 'trellin#organizations'
  match 'push' => 'trellin#push'

  root :to => 'static#index'

end

app/models/credential.rb
class Credential < ActiveRecord::Base

  belongs_to :user

end

app/controllers/credentials_controller.rb
class CredentialsController < ApplicationController
  # GET /credentials
  # GET /credentials.json
  def index
    @credentials = Credential.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credentials }
    end
  end

  # GET /credentials/1
  # GET /credentials/1.json
  def show
    @credential = Credential.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @credential }
    end
  end

  # GET /credentials/new
  # GET /credentials/new.json
  def new
    @credential = Credential.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credential }
    end
  end

  # GET /credentials/1/edit
  def edit
    @credential = Credential.find(params[:id])
  end

  # POST /credentials
  # POST /credentials.json
  def create
    @credential = Credential.new(params[:credential])

    respond_to do |format|
      if @credential.save
        format.html { redirect_to @credential, notice: 'Credential was successfully created.' }
        format.json { render json: @credential, status: :created, location: @credential }
      else
        format.html { render action: "new" }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /credentials/1
  # PUT /credentials/1.json
  def update
    @credential = Credential.find(params[:id])

    respond_to do |format|
      if @credential.update_attributes(params[:credential])
        format.html { redirect_to @credential, notice: 'Credential was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @credential.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credentials/1
  # DELETE /credentials/1.json
  def destroy
    @credential = Credential.find(params[:id])
    @credential.destroy

    respond_to do |format|
      format.html { redirect_to credentials_url }
      format.json { head :ok }
    end
  end
end

app/helpers/credentials_helper.rb
module CredentialsHelper
end

app/views/credentials/_form.html.erb
<%= form_for(@credential) do |f| %>
  <% if @credential.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credential.errors.count, "error") %> prohibited this credential from being saved:</h2>

      <ul>
      <% @credential.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :uid %><br />
    <%= f.text_field :uid %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :nickname %><br />
    <%= f.text_field :nickname %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credentials/edit.html.erb
<h1>Editing credential</h1>

<%= render 'form' %>

<%= link_to 'Show', @credential %> |
<%= link_to 'Back', credentials_path %>

app/views/credentials/index.html.erb
<h1>Listing credentials</h1>

<table>
  <tr>
    <th>Provider</th>
    <th>Uid</th>
    <th>Name</th>
    <th>Email</th>
    <th>Nickname</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @credentials.each do |credential| %>
  <tr>
    <td><%= credential.provider %></td>
    <td><%= credential.uid %></td>
    <td><%= credential.name %></td>
    <td><%= credential.email %></td>
    <td><%= credential.nickname %></td>
    <td><%= link_to 'Show', credential %></td>
    <td><%= link_to 'Edit', edit_credential_path(credential) %></td>
    <td><%= link_to 'Destroy', credential, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Credential', new_credential_path %>

app/views/credentials/new.html.erb
<h1>New credential</h1>

<%= render 'form' %>

<%= link_to 'Back', credentials_path %>

app/views/credentials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Provider:</b>
  <%= @credential.provider %>
</p>

<p>
  <b>Uid:</b>
  <%= @credential.uid %>
</p>

<p>
  <b>Name:</b>
  <%= @credential.name %>
</p>

<p>
  <b>Email:</b>
  <%= @credential.email %>
</p>

<p>
  <b>Nickname:</b>
  <%= @credential.nickname %>
</p>


<%= link_to 'Edit', edit_credential_path(@credential) %> |
<%= link_to 'Back', credentials_path %>